<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_LoadingStation" Id="{0739b0e9-6a0b-43e8-b760-d31010e6020e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LoadingStation IMPLEMENTS I_WorkingStation
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="prTableRotationInterlock" Id="{e5fc254a-5609-4be3-84a7-f8c244dac0b1}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY prTableRotationInterlock : BOOL
]]></Declaration>
      <Get Name="Get" Id="{b7a6cd8a-205a-4ef0-80ee-061e503f9f54}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{dd4a82e4-3071-4331-955b-6cba30b3edf6}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="prTableRotationRequest" Id="{4f6b0926-f186-40fb-a73a-e615918a2a53}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY prTableRotationRequest : BOOL
]]></Declaration>
      <Get Name="Get" Id="{e1c3145f-d20b-41e6-89c1-66bdfe48409e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{cd771a07-006e-4e10-81db-f4cea774d852}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="FB_LoadingStation">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_LoadingStation.prTableRotationInterlock.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_LoadingStation.prTableRotationInterlock.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_LoadingStation.prTableRotationRequest.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_LoadingStation.prTableRotationRequest.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>