<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_UnloadingStation" Id="{296f6eb6-2953-417c-abf3-86065ed0eed9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_UnloadingStation IMPLEMENTS I_WorkingStation
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="prTableRotationInterlock" Id="{88e14835-694a-42c6-83c2-cd76547a82a6}">
      <Declaration><![CDATA[{attribue 'monitoring':= call}
PROPERTY prTableRotationInterlock : BOOL
]]></Declaration>
      <Get Name="Get" Id="{dad85451-5c00-40c4-980f-760fb8b97cd8}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{e168513b-10c3-41ca-b98a-85bf4d086b6b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="prTableRotationRequest" Id="{42e13d42-38a7-4f24-9a20-9aec86822997}">
      <Declaration><![CDATA[{attribue 'monitoring':= call}
PROPERTY prTableRotationRequest : BOOL
]]></Declaration>
      <Get Name="Get" Id="{9d27c0c8-5d5b-424c-b898-aac61aa96673}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{8767d4b8-41d1-4d46-9c1a-a16455f23c2f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="FB_UnloadingStation">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_UnloadingStation.prTableRotationInterlock.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UnloadingStation.prTableRotationInterlock.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UnloadingStation.prTableRotationRequest.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UnloadingStation.prTableRotationRequest.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>